// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n'

export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = {
	/**
	 * Configure Grid
	 */
	'ConfigureGrid': string
	/**
	 * Columns
	 */
	'Columns': string
	/**
	 * Rows
	 */
	'Rows': string
	/**
	 * Not enough entries to fill the grid !
	 */
	'AlertNotEnoughEntriesToFillTheGrid': string
	/**
	 * Add entries or reduce grid dimensions to start the game.
	 */
	'AddEntriesOrReduceGridDimensionsToStartTheGame': string
	/**
	 * Confirmation time (in minutes)
	 */
	'ConfirmationTime': string
	/**
	 * Save
	 */
	'SaveGame': string
	/**
	 * Start
	 */
	'StartGame': string
}

export type TranslationFunctions = {
	/**
	 * Configure Grid
	 */
	'ConfigureGrid': () => LocalizedString
	/**
	 * Columns
	 */
	'Columns': () => LocalizedString
	/**
	 * Rows
	 */
	'Rows': () => LocalizedString
	/**
	 * Not enough entries to fill the grid !
	 */
	'AlertNotEnoughEntriesToFillTheGrid': () => LocalizedString
	/**
	 * Add entries or reduce grid dimensions to start the game.
	 */
	'AddEntriesOrReduceGridDimensionsToStartTheGame': () => LocalizedString
	/**
	 * Confirmation time (in minutes)
	 */
	'ConfirmationTime': () => LocalizedString
	/**
	 * Save
	 */
	'SaveGame': () => LocalizedString
	/**
	 * Start
	 */
	'StartGame': () => LocalizedString
}

export type Formatters = {}
