// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Mobile: {
		/**
		 * C​o​n​f​i​r​m
		 */
		ConfirmButton: string
		/**
		 * C​a​n​c​e​l
		 */
		CancelButton: string
		/**
		 * M​i​s​s​e​d
		 */
		MissedLabel: string
		/**
		 * P​e​n​d​i​n​g
		 */
		PendingLabel: string
	}
	OverlayBingoGrid: {
		/**
		 * W​a​i​t​i​n​g​ ​f​o​r​ ​t​h​e​ ​g​a​m​e​ ​t​o​ ​s​t​a​r​t​ ​!
		 */
		WaitingMessage: string
		/**
		 * I​n​ ​o​r​d​e​r​ ​t​o​ ​j​o​i​n​ ​t​h​e​ ​g​a​m​e​ ​a​n​d​ ​g​e​t​ ​y​o​u​r​ ​o​w​n​ ​B​i​n​g​o​ ​g​r​i​d​,​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​s​h​a​r​e​ ​y​o​u​r​ ​T​w​i​t​c​h​ ​u​s​e​r​n​a​m​e​ ​w​i​t​h​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​.
		 */
		IdentityPromptMessage: string
		/**
		 * S​h​a​r​e
		 */
		ShareIdentityButtonLabel: string
	}
	BingoViewerEntry: {
		/**
		 * C​o​n​f​i​r​m
		 */
		ConfirmButtonLabel: string
		/**
		 * M​i​s​s​e​d
		 */
		MissedRibbonLabel: string
	}
	BingoModeration: {
		/**
		 * C​o​n​f​i​r​m
		 */
		ConfirmButtonLabel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		ConfirmButton: string
		/**
		 * N​o​ ​e​n​t​r​i​e​s​ ​c​o​n​f​i​g​u​r​e​d​.
		 */
		NoEntriesMessage: string
	}
	Config: {
		/**
		 * C​o​n​f​i​g​u​r​e​ ​G​r​i​d
		 */
		ConfigureGrid: string
		/**
		 * C​o​l​u​m​n​s
		 */
		Columns: string
		/**
		 * R​o​w​s
		 */
		Rows: string
		/**
		 * N​o​t​ ​e​n​o​u​g​h​ ​e​n​t​r​i​e​s​ ​t​o​ ​f​i​l​l​ ​t​h​e​ ​g​r​i​d​ ​!
		 */
		AlertNotEnoughEntriesToFillTheGrid: string
		/**
		 * A​d​d​ ​e​n​t​r​i​e​s​ ​o​r​ ​r​e​d​u​c​e​ ​g​r​i​d​ ​d​i​m​e​n​s​i​o​n​s​ ​t​o​ ​s​t​a​r​t​ ​t​h​e​ ​g​a​m​e​.
		 */
		AddEntriesOrReduceGridDimensionsToStartTheGame: string
		/**
		 * C​o​n​f​i​r​m​a​t​i​o​n​ ​t​i​m​e
		 */
		ConfirmationTime: string
		/**
		 * S​a​v​e
		 */
		SaveGame: string
		/**
		 * S​t​a​r​t
		 */
		StartGame: string
		LibraryEditor: {
			/**
			 * L​i​b​r​a​r​y
			 */
			Title: string
			/**
			 * L​o​a​d​,​ ​p​a​s​t​e​ ​o​r​ ​a​d​d​ ​a​l​l​ ​y​o​u​r​ ​b​i​n​g​o​ ​e​n​t​r​i​e​s​ ​h​e​r​e​.
			 */
			TitleSubHeader: string
			/**
			 * N​o​ ​i​t​e​m​s​ ​i​n​ ​B​i​n​g​o​,​ ​g​o​ ​a​d​d​ ​s​o​m​e​ ​!
			 */
			MessageNoItems: string
			/**
			 * U​p​l​o​a​d​ ​e​n​t​r​y​ ​l​i​s​t
			 */
			UploadButtonLabel: string
			/**
			 * R​e​p​l​a​c​e​ ​e​n​t​r​i​e​s​ ​b​y​ ​u​p​l​o​a​d​i​n​g​ ​a​ ​.​t​x​t​ ​f​i​l​e
			 */
			UploadButtonTitle: string
			/**
			 * A​d​d​ ​a​ ​n​e​w​ ​e​n​t​r​y
			 */
			AddEntryButtonLabel: string
			/**
			 * A​d​d​ ​a​ ​n​e​w​ ​e​n​t​r​y​ ​t​o​ ​t​h​e​ ​l​i​s​t
			 */
			AddEntryButtonTitle: string
			/**
			 * C​o​p​y​ ​e​n​t​r​i​e​s
			 */
			CopyEntriesToPasteboardLabel: string
			/**
			 * C​o​p​y​ ​e​n​t​r​i​e​s​ ​t​o​ ​c​l​i​p​b​o​a​r​d
			 */
			CopyEntriesToPasteboardTitle: string
		}
		StatusCard: {
			/**
			 * S​t​a​t​u​s
			 */
			Title: string
			/**
			 * A​c​t​i​v​e
			 */
			StatusActive: string
			/**
			 * I​n​a​c​t​i​v​e
			 */
			StatusInactive: string
			/**
			 * S​t​o​p​ ​g​a​m​e
			 */
			StopButton: string
			/**
			 * L​o​a​d​i​n​g​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​.​.​.
			 */
			LoadingConfiguration: string
		}
		GameLog: {
			/**
			 * G​a​m​e​ ​L​o​g
			 */
			Header: string
			/**
			 * G​a​m​e​ ​s​t​a​r​t​e​d​ ​!
			 */
			StartedGameText: string
			/**
			 * #​{​e​n​t​r​y​K​e​y​}​ ​“​{​e​n​t​r​y​T​e​x​t​}​”​ ​c​o​n​f​i​r​m​e​d​ ​b​y​ ​{​p​l​a​y​e​r​N​a​m​e​s​}
			 * @param {unknown} entryKey
			 * @param {unknown} entryText
			 * @param {unknown} playerNames
			 */
			ConfirmationText: RequiredParams<'entryKey' | 'entryText' | 'playerNames'>
			/**
			 * #​{​e​n​t​r​y​K​e​y​}​ ​c​o​m​p​l​e​t​e​d​ ​c​o​l​u​m​n​s​ ​f​o​r​ ​{​p​l​a​y​e​r​s​C​o​u​n​t​}​ ​p​l​a​y​e​r​s
			 * @param {unknown} entryKey
			 * @param {unknown} playersCount
			 */
			CompletedColText: RequiredParams<'entryKey' | 'playersCount'>
			/**
			 * #​{​e​n​t​r​y​K​e​y​}​ ​c​o​m​p​l​e​t​e​d​ ​r​o​w​s​ ​f​o​r​ ​{​p​l​a​y​e​r​s​C​o​u​n​t​}​ ​p​l​a​y​e​r​s
			 * @param {unknown} entryKey
			 * @param {unknown} playersCount
			 */
			CompletedRowText: RequiredParams<'entryKey' | 'playersCount'>
			/**
			 * #​{​e​n​t​r​y​K​e​y​}​ ​c​o​m​p​l​e​t​e​d​ ​t​h​e​ ​g​r​i​d​ ​f​o​r​ ​{​p​l​a​y​e​r​s​C​o​u​n​t​}​ ​p​l​a​y​e​r​s
			 * @param {unknown} entryKey
			 * @param {unknown} playersCount
			 */
			CompletedGridText: RequiredParams<'entryKey' | 'playersCount'>
		}
		EntrySelectionView: {
			/**
			 * S​e​l​e​c​t​i​o​n
			 */
			Title: string
			/**
			 * T​h​e​s​e​ ​a​r​e​ ​t​h​e​ ​b​i​n​g​o​ ​e​n​t​r​i​e​s​ ​c​u​r​r​e​n​t​l​y​ ​s​e​l​e​c​t​e​d​ ​f​o​r​ ​t​h​e​ ​n​e​x​t​ ​g​a​m​e​.
			 */
			TitleSubHeader: string
			/**
			 * N​o​ ​i​t​e​m​s​ ​s​e​l​e​c​t​e​d
			 */
			NoItemMessage: string
		}
		EditableBingoEntry: {
			/**
			 * B​i​n​g​o​ ​p​r​o​p​o​s​i​t​i​o​n
			 */
			TextFieldLabel: string
			/**
			 * P​r​o​p​o​s​i​t​i​o​n
			 */
			TextFieldPlaceholder: string
			/**
			 * D​e​l​e​t​e​ ​t​h​i​s​ ​e​n​t​r​y
			 */
			DeleteLabel: string
			/**
			 * C​a​n​n​o​t​ ​d​e​l​e​t​e​ ​a​ ​s​e​l​e​c​t​e​d​ ​e​n​t​r​y
			 */
			DeleteLabelCantRemove: string
			/**
			 * A​d​d​ ​t​o​ ​s​e​l​e​c​t​i​o​n
			 */
			AddSelectionLabel: string
			/**
			 * E​d​i​t​ ​t​h​i​s​ ​e​n​t​r​y
			 */
			EditLabel: string
		}
		/**
		 * C​h​a​t​ ​i​n​t​e​g​r​a​t​i​o​n​ ​i​s​ ​e​n​a​b​l​e​d
		 */
		DeactivateChatIntegrationTitle: string
		/**
		 * Y​o​u​ ​c​a​n​ ​d​i​s​a​b​l​e​ ​c​h​a​t​ ​i​n​t​e​g​r​a​t​i​o​n​ ​b​y​ ​g​o​i​n​g​ ​t​o​ ​y​o​u​r​ ​“​M​y​ ​E​x​t​e​n​s​i​o​n​s​”​ ​p​a​n​e​l​,​ ​a​n​d​ ​c​l​i​c​k​i​n​g​ ​“​M​a​n​a​g​e​ ​P​e​r​m​i​s​s​i​o​n​s​”​.
		 */
		DeactivateChatIntegrationText: string
		/**
		 * C​h​a​t​ ​i​n​t​e​g​r​a​t​i​o​n​ ​i​s​ ​d​i​s​a​b​l​e​d
		 */
		ActivateChatIntegrationTitle: string
		/**
		 * Y​o​u​ ​c​a​n​ ​a​l​l​o​w​ ​c​h​a​t​ ​i​n​t​e​g​r​a​t​i​o​n​ ​b​y​ ​g​o​i​n​g​ ​t​o​ ​y​o​u​r​ ​“​M​y​ ​E​x​t​e​n​s​i​o​n​s​”​ ​p​a​n​e​l​,​ ​a​n​d​ ​c​l​i​c​k​i​n​g​ ​“​M​a​n​a​g​e​ ​P​e​r​m​i​s​s​i​o​n​s​”​.
		 */
		ActivateChatIntegrationText: string
	}
}

export type TranslationFunctions = {
	Mobile: {
		/**
		 * Confirm
		 */
		ConfirmButton: () => LocalizedString
		/**
		 * Cancel
		 */
		CancelButton: () => LocalizedString
		/**
		 * Missed
		 */
		MissedLabel: () => LocalizedString
		/**
		 * Pending
		 */
		PendingLabel: () => LocalizedString
	}
	OverlayBingoGrid: {
		/**
		 * Waiting for the game to start !
		 */
		WaitingMessage: () => LocalizedString
		/**
		 * In order to join the game and get your own Bingo grid, you need to share your Twitch username with the extension.
		 */
		IdentityPromptMessage: () => LocalizedString
		/**
		 * Share
		 */
		ShareIdentityButtonLabel: () => LocalizedString
	}
	BingoViewerEntry: {
		/**
		 * Confirm
		 */
		ConfirmButtonLabel: () => LocalizedString
		/**
		 * Missed
		 */
		MissedRibbonLabel: () => LocalizedString
	}
	BingoModeration: {
		/**
		 * Confirm
		 */
		ConfirmButtonLabel: () => LocalizedString
		/**
		 * Confirm
		 */
		ConfirmButton: () => LocalizedString
		/**
		 * No entries configured.
		 */
		NoEntriesMessage: () => LocalizedString
	}
	Config: {
		/**
		 * Configure Grid
		 */
		ConfigureGrid: () => LocalizedString
		/**
		 * Columns
		 */
		Columns: () => LocalizedString
		/**
		 * Rows
		 */
		Rows: () => LocalizedString
		/**
		 * Not enough entries to fill the grid !
		 */
		AlertNotEnoughEntriesToFillTheGrid: () => LocalizedString
		/**
		 * Add entries or reduce grid dimensions to start the game.
		 */
		AddEntriesOrReduceGridDimensionsToStartTheGame: () => LocalizedString
		/**
		 * Confirmation time
		 */
		ConfirmationTime: () => LocalizedString
		/**
		 * Save
		 */
		SaveGame: () => LocalizedString
		/**
		 * Start
		 */
		StartGame: () => LocalizedString
		LibraryEditor: {
			/**
			 * Library
			 */
			Title: () => LocalizedString
			/**
			 * Load, paste or add all your bingo entries here.
			 */
			TitleSubHeader: () => LocalizedString
			/**
			 * No items in Bingo, go add some !
			 */
			MessageNoItems: () => LocalizedString
			/**
			 * Upload entry list
			 */
			UploadButtonLabel: () => LocalizedString
			/**
			 * Replace entries by uploading a .txt file
			 */
			UploadButtonTitle: () => LocalizedString
			/**
			 * Add a new entry
			 */
			AddEntryButtonLabel: () => LocalizedString
			/**
			 * Add a new entry to the list
			 */
			AddEntryButtonTitle: () => LocalizedString
			/**
			 * Copy entries
			 */
			CopyEntriesToPasteboardLabel: () => LocalizedString
			/**
			 * Copy entries to clipboard
			 */
			CopyEntriesToPasteboardTitle: () => LocalizedString
		}
		StatusCard: {
			/**
			 * Status
			 */
			Title: () => LocalizedString
			/**
			 * Active
			 */
			StatusActive: () => LocalizedString
			/**
			 * Inactive
			 */
			StatusInactive: () => LocalizedString
			/**
			 * Stop game
			 */
			StopButton: () => LocalizedString
			/**
			 * Loading configuration ...
			 */
			LoadingConfiguration: () => LocalizedString
		}
		GameLog: {
			/**
			 * Game Log
			 */
			Header: () => LocalizedString
			/**
			 * Game started !
			 */
			StartedGameText: () => LocalizedString
			/**
			 * #{entryKey} “{entryText}” confirmed by {playerNames}
			 */
			ConfirmationText: (arg: { entryKey: unknown, entryText: unknown, playerNames: unknown }) => LocalizedString
			/**
			 * #{entryKey} completed columns for {playersCount} players
			 */
			CompletedColText: (arg: { entryKey: unknown, playersCount: unknown }) => LocalizedString
			/**
			 * #{entryKey} completed rows for {playersCount} players
			 */
			CompletedRowText: (arg: { entryKey: unknown, playersCount: unknown }) => LocalizedString
			/**
			 * #{entryKey} completed the grid for {playersCount} players
			 */
			CompletedGridText: (arg: { entryKey: unknown, playersCount: unknown }) => LocalizedString
		}
		EntrySelectionView: {
			/**
			 * Selection
			 */
			Title: () => LocalizedString
			/**
			 * These are the bingo entries currently selected for the next game.
			 */
			TitleSubHeader: () => LocalizedString
			/**
			 * No items selected
			 */
			NoItemMessage: () => LocalizedString
		}
		EditableBingoEntry: {
			/**
			 * Bingo proposition
			 */
			TextFieldLabel: () => LocalizedString
			/**
			 * Proposition
			 */
			TextFieldPlaceholder: () => LocalizedString
			/**
			 * Delete this entry
			 */
			DeleteLabel: () => LocalizedString
			/**
			 * Cannot delete a selected entry
			 */
			DeleteLabelCantRemove: () => LocalizedString
			/**
			 * Add to selection
			 */
			AddSelectionLabel: () => LocalizedString
			/**
			 * Edit this entry
			 */
			EditLabel: () => LocalizedString
		}
		/**
		 * Chat integration is enabled
		 */
		DeactivateChatIntegrationTitle: () => LocalizedString
		/**
		 * You can disable chat integration by going to your “My Extensions” panel, and clicking “Manage Permissions”.
		 */
		DeactivateChatIntegrationText: () => LocalizedString
		/**
		 * Chat integration is disabled
		 */
		ActivateChatIntegrationTitle: () => LocalizedString
		/**
		 * You can allow chat integration by going to your “My Extensions” panel, and clicking “Manage Permissions”.
		 */
		ActivateChatIntegrationText: () => LocalizedString
	}
}

export type Formatters = {}
