name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/lambda_deploy.yml
    with:
      environment: "AWS Staging Lambda"
      branch: ${{ github.event.inputs.branch }}
    secrets: inherit
