name: Deploy to Production

on:
  push:
    branches: [ "feature/aws-lambda-hosting" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/lambda_deploy.yml
    with:
      environment: "AWS Production Lambda"
      branch: main
    secrets: inherit