# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Package Twitch Extension

on:
  push:
    branches: [ main, "feature/*" ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Package Extension
      working-directory: ./twitch-bingo-extension
      run: |
        rm -rf node_modules && yarn install --frozen-lockfile
        yarn run build
    - name: Upload Twitch Extension Package
      uses: actions/upload-artifact@v2
      with:
        name: frontend-${{github.run_id}}
        path: ./twitch-bingo-extension/dist/
